#!/bin/sh

## Copyright (C) 2020 - 2021 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## https://savannah.nongnu.org/bugs/index.php?56767
## https://forums.whonix.org/t/hardened-malloc-hardened-memory-allocator/7474/105
## https://forums.whonix.org/t/hardened-malloc-hardened-memory-allocator/7474/109
## https://git.savannah.nongnu.org/cgit/man-db.git/tree/lib/sandbox.c#n142
## TODO: Debian bullseye
## Fixed in `man` upstream. Fix will probably arrive and can be removed in
## Debian bullseye and above.

if [ "$MAN_DISABLE_SECCOMP" = "" ]; then
   export MAN_DISABLE_SECCOMP=1
fi
