#!/usr/bin/dh-exec

## Copyright (C) 2020 - 2020 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

debian/hardened_malloc.conf => /etc/sysctl.d/hardened_malloc.conf
debian/50hardened-malloc => /etc/X11/Xsession.d/50hardened-malloc
debian/hardened-malloc-kicksecure => /etc/sudoers.d/hardened-malloc-kicksecure
debian/30_hardened-malloc-kicksecure.conf => /usr/lib/systemd/system.conf.d/30_hardened-malloc-kicksecure.conf
